### ISSUE TITLE
Inheritance of attribute `AssignWorker` from Interface to Implementation not functioning as expected

### ISSUE THREAD

**Issue by butschster** [spiral/temporal-bridge#48]
I recently attempted to use assign workers functionality to both workflows and activities via PHP attributes as per the provided documentation. Below is a simplified example to demonstrate my setup:

```php
// For workflows:
namespace App\Workflow;
use Spiral\TemporalBridge\Attribute\AssignWorker;
use Temporal\Workflow\WorkflowInterface;

#[AssignWorker(name: 'worker1')]
#[WorkflowInterface]
interface MoneyTransferWorkflowInterface { /*...*/ }
```

```php
// And for activities:
namespace App\Workflow;
use Spiral\TemporalBridge\Attribute\AssignWorker;
use Temporal\Activity\ActivityInterface;

#[AssignWorker(name: 'worker1')]
#[ActivityInterface(...)]
interface MoneyTransferActivityInterface { /*...*/ }
```

However, I discovered an issue where the `AssignWorker` attributes specified on the interfaces are not being recognized/utilized by the application. The attributes only appear to be effective when directly applied to the implementing classes.

From my understanding, the desired behavior would be for the `AssignWorker` attribute to be inherited or at least recognized from the interface to its implementation, which would simplify and centralize worker assignment, especially in projects with a large number of workflows and activities.

It would be beneficial to enhance the functionality to also check for `AssignWorker` attributes on the interfaces from which classes are derived. This would align with the typical expectation of attribute inheritance or recognition from interfaces to their implementations in PHP.

**Comment by butschster** [comment]
Will be improved by @roxblnfk in Temporal SDK

**Comment by roxblnfk** [comment]
In the event that the TaskQueue attribute is added to the Temporal PHP SDK, it will need to be supported in this bridge. However, I'm not sure that AssignWorker and TaskQueue carry the same semantic
